[package]
name = "zayden-graphics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
png = { workspace = true }
resvg = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }
tracing = { workspace = true }

[dev-dependencies]
png = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
