[package]
name = "palworld"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
zayden-app = { workspace = true }
zayden-core = { workspace = true }

itertools = { workspace = true }
jiff = { workspace = true, features = ["std"] }
jiff-cron = { workspace = true }
jiff-sqlx = { workspace = true }
moka = { workspace = true, features = ["future"] }
rayon = { workspace = true }
reqwest = { workspace = true, features = ["rustls", "http2", "json", "query"] }
scraper = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
serenity = { workspace = true, features = [
    "rustls_backend",
    "builder",
    "gateway",
] }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["fs", "rt", "sync"] }
tracing = { workspace = true }

flate2 = { workspace = true }
gvas = { workspace = true }
oozextract = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
tokio = { workspace = true, features = ["io-util", "macros", "net", "rt"] }

[[bench]]
name = "save"
harness = false

[[bench]]
name = "breeding"
harness = false
