[package]
name = "destiny2"
version = "0.1.0"
edition = "2024"

[dependencies]
destiny2-core = { workspace = true }
zayden-core = { workspace = true }

bungie-api = { workspace = true }

serenity = { workspace = true }
tokio = { workspace = true }
