default_job = "clippy"

[jobs.clippy]
command = [
    "cargo",
    "clippy",
    "--workspace",
    "--all-targets",
    "--color",
    "always",
    "--",
    "-D",
    "warnings",
]
need_stdout = false

[jobs.fmt]
command = ["cargo", "fmt", "--all", "--check"]
need_stdout = true

[jobs.test]
command = ["cargo", "test", "--workspace", "--all-targets", "--color", "always"]
need_stdout = true

[jobs.nextest]
command = [
    "cargo",
    "nextest",
    "run",
    "--workspace",
    "--all-targets",
    "--hide-progress-bar",
    "--failure-output",
    "final",
]
analyzer = "nextest"
need_stdout = true

[jobs.build]
command = ["cargo", "build", "--workspace", "--all-targets", "--color", "always"]
need_stdout = false

[jobs.check-ssr]
command = [
    "cargo",
    "check",
    "-p",
    "dashboard",
    "--features",
    "ssr",
    "--color",
    "always",
]
need_stdout = false

[jobs.check-hydrate]
command = [
    "cargo",
    "check",
    "-p",
    "dashboard",
    "--target",
    "wasm32-unknown-unknown",
    "--features",
    "hydrate",
    "--color",
    "always",
]
need_stdout = false

[jobs.clippy-hydrate]
command = [
    "cargo",
    "clippy",
    "-p",
    "dashboard",
    "--target",
    "wasm32-unknown-unknown",
    "--features",
    "hydrate",
    "--color",
    "always",
    "--",
    "-D",
    "warnings",
]
need_stdout = false

[jobs.check-offline]
command = ["cargo", "check", "--workspace", "--all-targets", "--color", "always"]
need_stdout = false
env.SQLX_OFFLINE = "true"

[jobs.check-offline-ssr]
command = [
    "cargo",
    "check",
    "-p",
    "dashboard",
    "--features",
    "ssr",
    "--color",
    "always",
]
need_stdout = false
env.SQLX_OFFLINE = "true"

[exports.locations]
auto = true
path = ".bacon-locations"
line_format = "{kind} {path}:{line}:{column} {message}"
