default_job = "clippy-workspace"

[jobs.clippy-workspace]
command = [
    "cargo",
    "clippy",
    "--workspace",
    "--all-targets",
    "--color",
    "always",
    "--",
    "-D",
    "warnings",
]
need_stdout = false

[jobs.check-ssr]
command = [
    "cargo",
    "check",
    "-p",
    "dashboard",
    "--features",
    "ssr",
    "--color",
    "always",
]
need_stdout = false

[jobs.check-hydrate]
command = [
    "cargo",
    "check",
    "-p",
    "dashboard",
    "--target",
    "wasm32-unknown-unknown",
    "--features",
    "hydrate",
    "--color",
    "always",
]
need_stdout = false

[jobs.test-workspace]
command = ["cargo", "test", "--color", "always"]
need_stdout = true

[jobs.check-offline]
command = ["cargo", "check", "--workspace", "--all-targets", "--color", "always"]
need_stdout = false
env.SQLX_OFFLINE = "true"

[jobs.check-offline-ssr]
command = [
    "cargo",
    "check",
    "-p",
    "dashboard",
    "--features",
    "ssr",
    "--color",
    "always",
]
need_stdout = false
env.SQLX_OFFLINE = "true"

[exports.locations]
auto = true
path = ".bacon-locations"
line_format = "{kind} {path}:{line}:{column} {message}"
