[package]
name = "zayden"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15.7"
rand = "0.8.5"
serde = "1.0.164"
serenity = { version = "0.11.5", default-features = false, features = [
    "builder",
    "collector",
    "client",
    "gateway",
    "model",
    "utils",
    "rustls_backend",
] }
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }
