[package]
name = "zayden"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
dotenvy = "0.15.7"
rand = "0.8.5"
regex = "1.8.4"
reqwest = "0.11.18"
serde = "1.0.164"
serde_json = "1.0.99"
sqlx = {version = "0.6.3", features=["chrono", "runtime-tokio-rustls", "postgres", "offline", "time"]}
tokio = { version = "1.28.2", features = ["macros", "rt-multi-thread"] }

[dependencies.serenity]
version = "0.11.5"
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "collector",
    "gateway",
    "model",
    "utils",
    "rustls_backend",
]
