[workspace]
resolver = "3"
members = [
    "bot",
    "zayden-core",
    "endgame-analysis",
    # "family",
    "gambling",
    # "gold-star",
    "levels",
    "lfg",
    "reaction-roles",
    "suggestions",
    "temp-voice",
    "ticket",
]

[workspace.dependencies]
zayden-core = { path = "./zayden-core" }
endgame-analysis = { path = "./endgame-analysis" }
gambling = { path = "./gambling" }
levels = { path = "./levels" }
lfg = { path = "./lfg" }
reaction-roles = { path = "./reaction-roles" }
suggestions = { path = "./suggestions" }
temp-voice = { path = "./temp-voice" }
ticket = { path = "./ticket" }

bungie-api = { git = "https://github.com/ViridianLink/bungie-api.git", branch = "main" }

async-trait = { version = "*", default-features = false }
bigdecimal = { version = "*", default-features = false }
chrono = { version = "*", default-features = false }
chrono-tz = { version = "*", default-features = false }
cron = { version = "*", default-features = false }
dotenvy = { version = "*", default-features = false }
futures = { version = "*", default-features = false }
num-format = { version = "*", default-features = false }
openai_api_rust = { version = "*", default-features = false }
rand = { version = "*", default-features = false }
rand_distr = { version = "*", default-features = false }
serde = { version = "*", default-features = false }
serde_json = { version = "*", default-features = false }
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next", default-features = true }


sqlx = { version = "*", default-features = false }
tokio = { version = "*", default-features = false }
time = { version = "*", default-features = false }
url = { version = "*", default-features = false }
walkdir = { version = "*", default-features = false }


[profile.release]
opt-level = 3
panic = "abort"
strip = true
codegen-units = 1
lto = "fat"
