[package]
name = "destiny2"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
bungie-api = { workspace = true }
futures = { workspace = true }
google-sheets-api = { workspace = true }
itertools = { workspace = true }
jiff-cron = { workspace = true }
serenity = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
zayden-core = { workspace = true }
