[package]
name = "gold-star"
version = "0.1.0"
edition = "2021"

[dependencies]
zayden-core = { workspace = true }

async-trait = { workspace = true }
chrono = { workspace = true }
serenity = { workspace = true }
sqlx = { workspace = true }
