//! Cookie-jar authentication for the `yt-dlp` child processes.
//!
//! A datacenter IP with no session eventually gets 403s from every player
//! client, so `--cookies` is the remedy. These tests pin the three ways that
//! remedy can quietly stop working:
//!
//! * a jar that parses but is read as anonymous (the `#HttpOnly_` trap),
//! * leases that collide or leak the credential into a shared temp directory,
//! * a stream-client list yt-dlp discards the moment it sees cookies.

use std::collections::HashSet;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

use music::{
    AUTHED_STREAM_CLIENTS,
    COOKIE_UNSUPPORTED_CLIENTS,
    CookieJar,
    JarStatus,
    STREAM_CLIENTS,
    cookie_warning,
    has_netscape_header,
    jar_status,
    parse_netscape,
    stream_clients,
};

const HEADER: &str = "# Netscape HTTP Cookie File\n";

/// A jar exported from a signed-in browser: the two `__Secure-*` session IDs
/// arrive `HttpOnly`, i.e. behind a leading `#`.
fn authenticated_jar(expiry: i64) -> String {
    format!(
        "{HEADER}# This file is generated by yt-dlp.  Do not edit.\n\
         \n\
         .youtube.com\tTRUE\t/\tTRUE\t{expiry}\tLOGIN_INFO\tAFmmF2s\n\
         #HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t{later}\t__Secure-3PAPISID\tabc/def\n\
         #HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t{later}\t__Secure-1PAPISID\tabc/def\n\
         .youtube.com\tTRUE\t/\tFALSE\t0\tPREF\ttz=Europe.London\n",
        later = expiry + 1_000,
    )
}

/// Everything a cookie exporter picks up from a *logged-out* visit.
fn anonymous_jar() -> String {
    format!(
        "{HEADER}\
         .youtube.com\tTRUE\t/\tFALSE\t2000000000\tPREF\ttz=Europe.London\n\
         .youtube.com\tTRUE\t/\tTRUE\t2000000000\tSOCS\tCAI\n\
         .youtube.com\tTRUE\t/\tTRUE\t2000000000\tVISITOR_INFO1_LIVE\tnope\n"
    )
}

/// Writes `contents` to a uniquely named file under the system temp directory
/// and returns its path. Cleaned up by [`TempFile`]'s drop.
struct TempFile(PathBuf);

impl TempFile {
    fn new(contents: &str) -> std::io::Result<Self> {
        static NEXT: AtomicU64 = AtomicU64::new(0);

        let path = std::env::temp_dir().join(format!(
            "zayden-cookie-test-{}-{}.txt",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        std::fs::write(&path, contents)?;
        Ok(Self(path))
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for TempFile {
    fn drop(&mut self) {
        let _ = std::fs::remove_file(&self.0);
    }
}

// ---------------------------------------------------------------------------
// Parsing
// ---------------------------------------------------------------------------

/// The trap this whole module exists to avoid. `__Secure-1PAPISID` and
/// `__Secure-3PAPISID` are `HttpOnly`, and exporters mark those lines with a
/// leading `#HttpOnly_`. A parser that drops comment lines *before* checking
/// for that prefix throws away exactly the cookies that prove the jar is signed
/// in — and then reports a perfectly good jar as anonymous.
#[test]
fn http_only_lines_are_cookies_not_comments() {
    let jar = authenticated_jar(2_000_000_000);
    let cookies = parse_netscape(&jar);

    let names: Vec<&str> = cookies.iter().map(|c| c.name).collect();
    assert!(
        names.contains(&"__Secure-3PAPISID"),
        "the HttpOnly session cookie was dropped as a comment: {names:?}",
    );

    let secure = cookies
        .iter()
        .find(|c| c.name == "__Secure-3PAPISID")
        .expect("the HttpOnly cookie is present");
    assert!(secure.http_only);
    assert_eq!(secure.domain, ".youtube.com");
}

#[test]
fn real_comments_and_blank_lines_are_skipped() {
    let jar = authenticated_jar(2_000_000_000);
    let cookies = parse_netscape(&jar);

    assert_eq!(
        cookies.len(),
        4,
        "expected exactly the four cookie lines, got {cookies:?}",
    );
    assert!(cookies.iter().all(|c| !c.name.starts_with('#')));
}

#[test]
fn a_zero_expiry_is_a_session_cookie_not_the_epoch() {
    let jar = authenticated_jar(2_000_000_000);
    let cookies = parse_netscape(&jar);

    let pref = cookies.iter().find(|c| c.name == "PREF").expect("PREF is present");
    assert_eq!(pref.expires, None);
}

#[test]
fn malformed_lines_are_ignored_rather_than_panicking() {
    let contents = format!(
        "{HEADER}not\tenough\tfields\n\
         \n\
         # a comment\n\
         .youtube.com\tTRUE\t/\tTRUE\t2000000000\tLOGIN_INFO\tv\n"
    );

    let cookies = parse_netscape(&contents);
    assert_eq!(cookies.len(), 1);
    assert_eq!(cookies.first().map(|c| c.name), Some("LOGIN_INFO"));
}

// ---------------------------------------------------------------------------
// Header validation
// ---------------------------------------------------------------------------

#[test]
fn accepts_the_header_variants_exporters_actually_emit() {
    assert!(has_netscape_header("# Netscape HTTP Cookie File\n.youtube.com\t"));
    assert!(has_netscape_header("# HTTP Cookie File\n"));
    assert!(has_netscape_header("\n\n#  netscape http cookie file  \n"));
}

/// The single most common operator mistake: pasting a `Cookie:` request header
/// out of devtools instead of exporting a cookies.txt file.
#[test]
fn rejects_a_file_that_is_not_a_cookie_jar() {
    assert!(!has_netscape_header("LOGIN_INFO=AFmmF2s; SAPISID=abc"));
    assert!(!has_netscape_header(""));
    assert!(!has_netscape_header("{\"cookies\": []}"));
}

// ---------------------------------------------------------------------------
// Authentication status
// ---------------------------------------------------------------------------

#[test]
fn a_signed_in_jar_is_authenticated_and_reports_its_earliest_expiry() {
    let status = jar_status(&authenticated_jar(1_900_000_000));

    assert_eq!(status, JarStatus::Authenticated { expires: Some(1_900_000_000) });
    assert!(status.is_authenticated());
}

#[test]
fn a_logged_out_export_is_anonymous() {
    let status = jar_status(&anonymous_jar());

    assert_eq!(status, JarStatus::Anonymous);
    assert!(!status.is_authenticated());
}

/// yt-dlp needs *both* halves: `LOGIN_INFO` survives logout in some exports,
/// and a bare session ID without it does not authenticate either.
#[test]
fn either_half_alone_is_not_a_session() {
    let login_only =
        format!("{HEADER}.youtube.com\tTRUE\t/\tTRUE\t2000000000\tLOGIN_INFO\tv\n");
    let sid_only = format!(
        "{HEADER}#HttpOnly_.youtube.com\tTRUE\t/\tTRUE\t2000000000\tSAPISID\tv\n"
    );

    assert_eq!(jar_status(&login_only), JarStatus::Anonymous);
    assert_eq!(jar_status(&sid_only), JarStatus::Anonymous);
}

/// Cookies scoped to another host never reach `youtube.com` requests, so a jar
/// full of them is not a YouTube session however well-formed it looks.
#[test]
fn cookies_for_another_domain_do_not_authenticate() {
    let contents = format!(
        "{HEADER}.google.com\tTRUE\t/\tTRUE\t2000000000\tLOGIN_INFO\tv\n\
         .google.com\tTRUE\t/\tTRUE\t2000000000\tSAPISID\tv\n"
    );

    assert_eq!(jar_status(&contents), JarStatus::Anonymous);
}

#[test]
fn expires_in_counts_down_and_goes_negative_once_stale() {
    let status = JarStatus::Authenticated { expires: Some(1_000) };

    assert_eq!(status.expires_in(400), Some(600));
    assert_eq!(status.expires_in(1_500), Some(-500));
    assert_eq!(JarStatus::Anonymous.expires_in(400), None);
    assert_eq!(JarStatus::Authenticated { expires: None }.expires_in(400), None);
}

// ---------------------------------------------------------------------------
// Opening a jar
// ---------------------------------------------------------------------------

#[test]
fn open_accepts_a_signed_in_jar() {
    let file = TempFile::new(&authenticated_jar(2_000_000_000))
        .expect("write the test cookie file");

    let jar = CookieJar::open(file.path().to_path_buf()).expect("open the jar");

    assert_eq!(jar.path(), file.path());
    assert!(jar.status().is_authenticated());
}

/// A jar with no session is a configuration mistake, not a fatal one: it opens,
/// so the bot can say so once at startup instead of failing every `/play`.
#[test]
fn open_accepts_an_anonymous_jar_so_the_bot_can_report_it() {
    let file = TempFile::new(&anonymous_jar()).expect("write the test cookie file");

    let jar = CookieJar::open(file.path().to_path_buf()).expect("open the jar");

    assert_eq!(jar.status(), JarStatus::Anonymous);
}

#[test]
fn open_rejects_a_file_that_is_not_a_cookie_jar() {
    let file = TempFile::new("LOGIN_INFO=AFmmF2s; SAPISID=abc\n")
        .expect("write the test cookie file");

    let err = CookieJar::open(file.path().to_path_buf())
        .expect_err("a pasted Cookie header must not be accepted");

    assert!(
        err.to_string().contains("Netscape"),
        "the error must name the format the operator has to produce: {err}",
    );
}

#[test]
fn open_reports_a_missing_file() {
    let missing = std::env::temp_dir().join("zayden-cookie-does-not-exist.txt");

    CookieJar::open(missing).expect_err("a missing jar must not open");
}

// ---------------------------------------------------------------------------
// Leases
// ---------------------------------------------------------------------------

/// yt-dlp rewrites whatever file `--cookies` names, persisting cookies YouTube
/// rotated mid-run. Handing it the configured file directly would let two
/// concurrent resolutions interleave writes into the operator's credential —
/// and would break a read-only mount. Each run gets a copy instead.
#[tokio::test]
async fn a_lease_is_a_copy_that_leaves_the_configured_file_alone() {
    let contents = authenticated_jar(2_000_000_000);
    let file = TempFile::new(&contents).expect("write the test cookie file");
    let jar = CookieJar::open(file.path().to_path_buf()).expect("open the jar");

    let lease = jar.lease().await.expect("take a lease");

    assert_ne!(lease.path(), jar.path(), "the lease must not alias the jar");
    assert_eq!(
        std::fs::read_to_string(lease.path()).expect("read the lease"),
        contents,
        "the lease must carry the same session",
    );
    assert_eq!(lease.arg(), lease.path().to_string_lossy());

    // Stand in for yt-dlp's write-back.
    std::fs::write(lease.path(), "# Netscape HTTP Cookie File\n")
        .expect("overwrite the lease");

    assert_eq!(
        std::fs::read_to_string(jar.path()).expect("read the jar"),
        contents,
        "yt-dlp writing to its copy must not touch the configured file",
    );
}

#[tokio::test]
async fn concurrent_leases_never_share_a_path() {
    let file = TempFile::new(&authenticated_jar(2_000_000_000))
        .expect("write the test cookie file");
    let jar = CookieJar::open(file.path().to_path_buf()).expect("open the jar");

    let mut leases = Vec::new();
    for _ in 0..16 {
        leases.push(jar.lease().await.expect("take a lease"));
    }

    let paths: HashSet<PathBuf> =
        leases.iter().map(|lease| lease.path().to_path_buf()).collect();

    assert_eq!(
        paths.len(),
        leases.len(),
        "two concurrent yt-dlp runs would write over each other",
    );
}

#[tokio::test]
async fn dropping_a_lease_unlinks_the_copied_credential() {
    let file = TempFile::new(&authenticated_jar(2_000_000_000))
        .expect("write the test cookie file");
    let jar = CookieJar::open(file.path().to_path_buf()).expect("open the jar");

    let path = {
        let lease = jar.lease().await.expect("take a lease");
        assert!(lease.path().exists());
        lease.path().to_path_buf()
    };

    assert!(
        !path.exists(),
        "a session cookie copy was left behind in the temp directory",
    );
}

/// The lease sits in a world-writable shared directory, so it is created
/// private rather than chmod-ed afterwards — there is no window in which the
/// session is readable by other users on the host.
#[cfg(unix)]
#[tokio::test]
async fn a_lease_is_only_readable_by_this_user() {
    use std::os::unix::fs::PermissionsExt;

    let file = TempFile::new(&authenticated_jar(2_000_000_000))
        .expect("write the test cookie file");
    let jar = CookieJar::open(file.path().to_path_buf()).expect("open the jar");

    let lease = jar.lease().await.expect("take a lease");
    let mode = std::fs::metadata(lease.path())
        .expect("stat the lease")
        .permissions()
        .mode();

    assert_eq!(
        mode & 0o077,
        0,
        "the copied cookies are readable by other users (mode {:o})",
        mode & 0o777,
    );
}

/// A refreshed export should take effect without a restart, so the lease reads
/// the file each time rather than a snapshot taken at open.
#[tokio::test]
async fn a_lease_picks_up_a_jar_replaced_since_startup() {
    let file = TempFile::new(&authenticated_jar(1_000_000_000))
        .expect("write the test cookie file");
    let jar = CookieJar::open(file.path().to_path_buf()).expect("open the jar");

    let refreshed = authenticated_jar(2_000_000_000);
    std::fs::write(file.path(), &refreshed).expect("re-export the jar");

    let lease = jar.lease().await.expect("take a lease");

    assert_eq!(
        std::fs::read_to_string(lease.path()).expect("read the lease"),
        refreshed,
    );
}

// ---------------------------------------------------------------------------
// Player clients
// ---------------------------------------------------------------------------

/// The regression this list exists for. Once yt-dlp sees account cookies it
/// drops every requested client whose innertube profile is not
/// `SUPPORTS_COOKIES` — and since each attempt requests exactly one client, a
/// dropped client is an attempt that asks for nothing at all. Reusing the
/// anonymous list would waste half the fallback chain (`android_vr` and
/// `tv_simply`) on the very path the cookies were added to rescue.
#[test]
fn the_authenticated_clients_all_survive_yt_dlps_cookie_filter() {
    for client in AUTHED_STREAM_CLIENTS {
        assert!(
            !COOKIE_UNSUPPORTED_CLIENTS.contains(client),
            "yt-dlp discards `{client}` when cookies are supplied, so that \
             attempt would resolve nothing",
        );
    }
}

#[test]
fn the_anonymous_list_is_unchanged_when_no_jar_is_configured() {
    assert_eq!(stream_clients(false), STREAM_CLIENTS);
    assert_eq!(stream_clients(true), AUTHED_STREAM_CLIENTS);
}

#[test]
fn both_client_lists_are_non_empty_and_free_of_duplicates() {
    const EMPTY: &[&str] = &[];

    for list in [STREAM_CLIENTS, AUTHED_STREAM_CLIENTS] {
        assert_ne!(list, EMPTY, "a stream-client list is empty");

        let unique: HashSet<&&str> = list.iter().collect();
        assert_eq!(unique.len(), list.len(), "duplicate client in {list:?}");
    }
}

// ---------------------------------------------------------------------------
// Expiry reporting
// ---------------------------------------------------------------------------

/// yt-dlp downgrades a dead session to a *warning* and carries on
/// unauthenticated, so the symptom is the original 403s returning with no
/// explanation. This is what turns that back into a diagnosable event.
#[test]
fn a_rotated_session_is_picked_out_of_yt_dlp_stderr() {
    let stderr = "\
[youtube] Extracting URL: https://www.youtube.com/watch?v=abc\n\
WARNING: The provided YouTube account cookies are no longer valid. They have \
likely been rotated in the browser as a security measure.\n\
[youtube] abc: Downloading webpage\n";

    let warning = cookie_warning(stderr).expect("the rotation warning is found");

    assert!(warning.contains("no longer valid"));
}

#[test]
fn ordinary_stderr_chatter_is_not_reported_as_a_cookie_problem() {
    let stderr = "\
[youtube] Extracting URL: https://www.youtube.com/watch?v=abc\n\
[youtube] abc: Downloading tv client config\n\
WARNING: Falling back to generic n function search\n";

    assert_eq!(cookie_warning(stderr), None);
}
