[package]
name = "zayden-core"
version = "0.9.0"
edition = "2024"


[dependencies]
async-trait = { workspace = true }
cron = { workspace = true }
serenity = { workspace = true, features = ["rustls_backend", "gateway"] }
sqlx = { workspace = true }
tokio = { workspace = true }
