[package]
name = "watch"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
ai = { workspace = true }
jellyfin = { workspace = true }
zayden-app = { workspace = true }
zayden-core = { workspace = true }

futures = { workspace = true, features = ["std", "async-await"] }
image = { workspace = true }
jiff = { workspace = true }
jiff-cron = { workspace = true }
jiff-sqlx = { workspace = true }
quick-xml = { workspace = true }
reqwest = { workspace = true, features = ["rustls", "http2", "json", "query"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serenity = { workspace = true }
sqlx = { workspace = true, features = ["migrate"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["time", "rt", "sync"] }
tracing = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
