[package]
name = "music"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.cargo-machete]
ignored = ["symphonia"]

[lints]
workspace = true

[dependencies]
zayden-app = { workspace = true }
zayden-core = { workspace = true }

async-trait = { workspace = true }
dashmap = { workspace = true }
rand = { workspace = true, features = ["thread_rng"] }
reqwest = { workspace = true }
rspotify = { workspace = true, features = [
    "client-reqwest",
    "reqwest-rustls-tls",
] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }
serenity = { workspace = true }
songbird = { workspace = true, features = [
    "driver",
    "gateway",
    "rustls",
    "serenity",
    "tungstenite",
] }
sqlx = { workspace = true }
symphonia = { workspace = true, features = ["mkv", "isomp4", "aac", "mp3"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = [
    "fs",
    "io-util",
    "process",
    "time",
] }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = [
    "macros",
    "rt",
    "net",
    "io-util",
    "process",
] }
