[package]
name = "temp-voice"
version = "0.1.0"
edition = "2024"

[dependencies]
zayden-core = { workspace = true }

async-trait = { workspace = true }
futures = { workspace = true }
serenity = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
