[package]
name = "family"
version = "0.1.0"
edition = "2021"

[dependencies]
zayden-core = { workspace = true }

async-trait = { workspace = true }
sqlx = { workspace = true }
futures = { workspace = true }
charming = { workspace = true }
serenity = { workspace = true }
