[package]
name = "hosting"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
zayden-app = { workspace = true }
zayden-core = { workspace = true }

jiff = { workspace = true, features = ["std"] }
jiff-cron = { workspace = true }
jiff-sqlx = { workspace = true }
rand = { workspace = true, features = ["std", "std_rng"] }
reqwest = { workspace = true, features = ["rustls", "http2", "json", "query"] }
serde = { workspace = true, features = ["derive"] }
serenity = { workspace = true }
sqlx = { workspace = true, features = ["macros", "migrate"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync", "time"] }
tracing = { workspace = true }

[dev-dependencies]
sqlx = { workspace = true, features = ["migrate"] }
tokio = { workspace = true, features = ["macros", "net", "rt-multi-thread"] }
